### Welcome endpoint
GET http://localhost:3000/

### get a report
GET http://localhost:3000/api/v1/reports/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdDQuY29tIiwiZXhwIjoxNzM1NDYxMDk4LCJpZCI6MX0.31dDW7MVHHOvBKFeUzrpynE0B6OgKxKVlX7C_ywxO0o

### get all reports
GET http://localhost:3000/api/v1/reports/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdDQuY29tIiwiZXhwIjoxNzM1NDYxMDk4LCJpZCI6MX0.31dDW7MVHHOvBKFeUzrpynE0B6OgKxKVlX7C_ywxO0o

### create a report
POST http://localhost:3000/api/v1/reports/
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdDQuY29tIiwiZXhwIjoxNzM1NDYxMDk4LCJpZCI6MX0.31dDW7MVHHOvBKFeUzrpynE0B6OgKxKVlX7C_ywxO0o

{
    "title": "sample",
    "content": "Here u got a report",
    "type": "report"
}

### update a report
PUT http://localhost:3000/api/v1/reports/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdDQuY29tIiwiZXhwIjoxNzM1NDYxMDk4LCJpZCI6MX0.31dDW7MVHHOvBKFeUzrpynE0B6OgKxKVlX7C_ywxO0o

{
    "title": "sample",
    "content": "update 1",
    "type": "report"
}

### delete a report
DELETE http://localhost:3000/api/v1/reports/9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdDQuY29tIiwiZXhwIjoxNzM1NDYxMDk4LCJpZCI6MX0.31dDW7MVHHOvBKFeUzrpynE0B6OgKxKVlX7C_ywxO0o

### Login endpoint
POST http://localhost:3000/users/login
content-type: application/json

{
    "email": "test@test4.com",
    "password": "password"
}

### Register endpoint
POST http://localhost:3000/users/register
content-type: application/json

{
    "name": "test",
    "password": "password",
    "email": "test@test4.com"
}

### JWT token endpoint
GET http://localhost:3000/users/token

### List of users
GET http://localhost:3000/users