### Welcome endpoint
GET http://localhost:3000/

### get a report
GET http://localhost:3000/api/v1/reports/1

### get all reports
GET http://localhost:3000/api/v1/reports/

### create a report
POST http://localhost:3000/api/v1/reports/
content-type: application/json

{
    "title": "sample",
    "content": "Here u got a report",
    "type": "report"
}

### update a report
PUT http://localhost:3000/api/v1/reports/1
content-type: application/json

{
    "title": "sample",
    "content": "update 1",
    "type": "report"
}

### delete a report
DELETE http://localhost:3000/api/v1/reports/9
